### ISSUE TITLE
add gatling simulation test to travis-ci

### ISSUE THREAD

**Issue by chepk** [TinkoffCreditSystems/gatling-picatinny#30]
Add build and run gatling simulation step to travis-ci.

* travis-ci.yaml:
```yaml
include:
  - stage: Tests
    name: Simulation test
    script:
    - sbt example/gatling:testOnly
```
* example project: add debug simulation with 1 user & 30 seconds duration
* investigate [travis services](https://docs.travis-ci.com/user/database-setup/#starting-services), try to use nginx container for testing simulation
